extends SceneTree
var game: Control
func _initialize() -> void:
	call_deferred("run")

func run() -> void:
	game = load("res://scenes/containment/main.tscn").instantiate()
	root.add_child(game)
	game.set_process(false)
	await process_frame
	await game.capture("00-home")
	game.ui.floor_plan()
	await game.capture("01-map")
	game.close_modal()
	game.perform("depart")
	game.perform("down")
	game.activate("stranger",Rect2())
	await game.capture("02-choices")
	game.close_modal()
	for id in ["paper","read_note","continue","seam","verify"]: game.perform(id)
	game.ui.containment()
	await game.capture("03-containment")
	game.close_modal()
	game.perform("contain:person")
	game.ui.timeline()
	await game.capture("04-timeline")
	game.perform("rewind:inspect")
	for id in ["verify","contain:boundary","return_success","put_away"]: game.perform(id)
	game.perform("auto:M01")
	game.perform("peek")
	game.tick_simulation(24)
	await game.capture("05-peephole")
	game.perform("room_entry")
	game.perform("recall")
	game.tick_simulation(21)
	game.perform("claim")
	game.perform("room_desk")
	game.ui.workshop()
	await game.capture("06-workshop")
	game.perform("decompose_all")
	game.ui.skills()
	await game.capture("07-skills")
	game.close_modal()
	for i in range(29):
		for id in ["depart","down","paper","read_note","continue","seam","verify","contain:boundary","return_success","put_away"]: game.perform(id)
	game.perform("auto:M01")
	game.tick_simulation(990)
	game.perform("auto:M02")
	game.tick_simulation(450)
	game.perform("recall")
	game.tick_simulation(45)
	game.ui.collection()
	await game.capture("08-collection")
	game.close_modal()
	game.perform("room_bedroom")
	game.model.s.companion_time = 0
	game.render()
	await game.capture("09-companion")
	game.ui.timer()
	await game.capture("10-timer")
	game.close_modal()
	game.ui.title_screen()
	await game.capture("11-title")
	game.close_modal()
	var i = 12
	for room in game.model.room_ids():
		game.model.s.companion_time = {"bedroom":0,"kitchen":45,"bathroom_laundry":90,"balcony_sky":135,"hall_table":180}.get(room,0)
		game.perform("room_"+room)
		await game.capture("%02d-room-%s"%[i,room])
		i += 1
	print("FULL_CAPTURE complete")
	quit()
