extends SceneTree
const Model = preload("res://scripts/containment/model.gd")
const Store = preload("res://scripts/save_store.gd")
var checks = 0
var failures = 0
var game: Control

func check(ok: bool, label: String) -> void:
	checks += 1
	if not ok:
		failures += 1
		printerr("FAIL FULL: "+label)

func valid(m: RefCounted, label: String) -> void:
	check(Model.new().restore(m.export_state()),"valid snapshot "+label)

func solve(m: RefCounted) -> void:
	for id in ["depart","down","paper","read_note","continue","listen","seam","verify","contain:boundary","return_success","put_away"]:
		check(m.act(id).get("changed",false),"route action "+id)
		valid(m,id)

func model_checks() -> void:
	var m = Model.new()
	check(m.catalog.size()==30 and m.by_id.size()==30,"30 unique definitions")
	valid(m,"new")
	check(m.act("auto:M01").is_empty(),"uncollected cannot auto")
	m.act("depart")
	check(m.act("contain:boundary").is_empty(),"cannot contain outside contact point")
	check(m.act("inspect").is_empty(),"locked ability route cannot bypass")
	for id in ["down","paper","continue","seam"]: m.act(id)
	check(not m.verified() and m.act("contain:boundary").is_empty(),"random clicks cannot substitute evidence")
	m.act("verify")
	check(not m.s.flags.has("connection"),"verification needs a clue")
	m.act("rewind:note")
	m.act("read_note")
	m.act("continue")
	m.act("seam")
	m.act("verify")
	check(m.verified(),"initial stats allow verified path")
	m.act("contain:person")
	check(m.s.mode=="dead" and m.s.used and m.s.cards.is_empty(),"incorrect target consumes opportunity and dies")
	var dead = m.export_state()
	check(m.act("contain:boundary").is_empty() and m.s==dead,"cannot try a second target after death")
	check(m.act("rewind:danger").is_empty(),"unvisited checkpoint unavailable")
	m.act("rewind:inspect")
	check(m.s.mode=="story" and not m.s.used and not m.s.flags.has("connection"),"rewind restores exact branch state")
	check(m.s.cases.M01.knowledge.has("connection"),"rewind retains learned information")
	m.act("verify")
	m.act("contain:boundary")
	m.act("return_success")
	check(m.s.cards.M01.progress==1 and m.s.completed_runs==1,"first completion exactly once")
	var first_items = m.s.inbox.duplicate()
	check(m.act("return_success").is_empty(),"reward screen cannot duplicate first reward")
	m.act("put_away")
	m.act("rewind:inspect")
	m.act("verify")
	m.act("contain:boundary")
	m.act("return_success")
	check(m.s.inbox==first_items and m.s.cards.M01.progress==1,"timeline replay cannot farm first reward")
	m.act("put_away")
	m.act("lock")
	check(m.act("depart").is_empty(),"locked door blocks exploration")
	m.act("lock")
	check(m.s.case_id!="M01" and not m.s.cards.has(m.s.case_id),"unlock selects a different uncollected case")
	check(m.s.cases[m.s.case_id].knowledge.is_empty(),"case evidence is independent")
	solve(m)
	var another = m.s.case_id
	check(m.s.cards.size()==2 and m.s.cards.M01.progress==1,"second instance has independent collection")
	m.act("claim")
	var bag = m.s.bag.duplicate()
	check(m.act("claim").is_empty() and m.s.bag==bag,"double claim safe")
	m.act("decompose:item_0:1")
	check(m.s.points["0"]==3 and m.s.points["1"]==1,"recipe creates distinct resources")
	var before_bad = m.export_state()
	check(m.act("decompose:item_0:9999").is_empty() and m.s==before_bad,"overspend rejected atomically")
	m.act("upgrade:perception")
	check(m.s.skills.perception==2 and m.s.points["0"]==1 and m.s.points["1"]==0,"upgrade exact costs")
	m.act("auto:M01")
	check(m.act("depart").is_empty() and m.act("lock").is_empty(),"actor cannot manually depart or change door while away")
	m.advance(17.5)
	m.act("room_desk")
	check(m.s.idle.elapsed==17.5,"room change doesn't reset round")
	var prior = m.export_state()
	check(not m.settle_round(2) and m.s==prior,"future round cannot settle")
	m.advance(27.5)
	check(m.s.cards.M01.progress==2 and m.s.cards[another].progress==1,"only selected type progresses")
	prior = m.export_state()
	check(not m.settle_round(1) and m.s==prior,"settlement is idempotent")
	m.act("peek")
	m.advance(450)
	check(m.tier("M01")=="gold" and m.s.cards.M01.progress==12,"exact half becomes gold")
	var inventory_before = int(m.s.inbox.item_0)
	m.advance(45)
	check(m.s.inbox.item_0-inventory_before==1,"gold drops reduced")
	m.act("recall")
	m.advance(45)
	check(not m.s.idle.active and m.s.room=="entry","recall settles current round and returns")
	valid(m,"gold recall")
	m.act("auto:M01")
	m.s.saved_at = 1000.0
	var offline = m.catch_up(1000.0+100000.0)
	check(offline.shiny and m.tier("M01")=="shiny" and not m.s.idle.active,"offline stops at shiny")
	check(m.s.cards.M01.samples.size()==23,"each finite sample counted once")
	prior = m.export_state()
	m.catch_up(101000.0)
	check(m.s==prior,"same timestamp cannot pay twice")
	check(m.act("auto:M01").is_empty() and m.act("replay:M01").is_empty(),"shiny closes both automatic and manual access")
	valid(m,"shiny")
	m.act("auto:"+another)
	m.s.paused = true
	prior = m.export_state()
	m.advance(600)
	check(m.s==prior,"pause stops progression")
	m.s.paused = false
	m.act("recall")
	m.advance(45)
	m.act("pomo_5")
	m.act("pomo_toggle")
	m.advance(300)
	check(m.s.pomo.phase=="break" and m.s.pomo.completed==1,"focus transitions to break once")
	m.advance(300)
	check(m.s.pomo.phase=="focus" and m.s.pomo.remaining==300,"break transitions to next focus")
	prior = m.export_state()
	for seconds in [-1,INF,NAN]: m.advance(seconds)
	check(m.s==prior,"bad deltas ignored")
	for field in ["points","cards","cases","idle","pomo"]:
		var bad = m.export_state()
		bad[field] = []
		var reader = Model.new()
		var clean = reader.export_state()
		check(not reader.restore(bad) and reader.s==clean,"invalid save nonmutating "+field)
	# All thirty are completed by the same real gameplay route, never by awarding cards.
	var full = Model.new()
	for i in range(30):
		solve(full)
	check(full.s.cards.size()==30,"all thirty accessible without upgrades")
	full.act("depart")
	check(full.s.ending_kind=="blocked","collected but not gold stops finale")
	full.act("ending_home")
	for entry in full.catalog:
		full.act("auto:"+entry.id)
		full.advance(450)
		full.act("recall")
		full.advance(45)
		check(full.tier(entry.id)=="gold","gold route "+entry.id)
		valid(full,"gold "+entry.id)
	full.act("depart")
	check(full.s.ending_kind=="false" and full.s.false_ending,"all gold false ending")
	full.act("ending_home")
	for entry in full.catalog:
		full.act("auto:"+entry.id)
		full.advance(540)
		check(full.tier(entry.id)=="shiny","shiny route "+entry.id)
		valid(full,"shiny "+entry.id)
	full.act("depart")
	check(full.s.ending_kind=="true" and full.s.true_ending,"all shiny true ending")
	valid(full,"ending")
	var final_store = Store.new("user://full-tests/all-complete.json")
	check(final_store.save(full.export_state()),"full save written")
	var loaded = Model.new()
	var restored = loaded.restore(final_store.load_primary())
	check(restored and JSON.stringify(loaded.s)==JSON.stringify(full.s),"full save round-trip")

func click(id: String) -> void:
	var target = game.find_child(id,true,false)
	check(target is Button,"button exists "+id)
	if not target is Button: return
	await process_frame
	var point = target.get_global_rect().get_center()
	var motion = InputEventMouseMotion.new()
	motion.position = point
	root.push_input(motion,true)
	for pressed in [true,false]:
		var event = InputEventMouseButton.new()
		event.position = point
		event.button_index = MOUSE_BUTTON_LEFT
		event.pressed = pressed
		root.push_input(event,true)
		await process_frame

func ui_checks() -> void:
	game = load("res://scenes/containment/main.tscn").instantiate()
	root.add_child(game)
	game.set_process(false)
	await process_frame
	await click("Depart")
	await click("EnterStory")
	check(game.model.s.mode=="story","actual door click enters story")
	await click("down")
	await click("paper")
	await click("read_note")
	await click("continue")
	await click("seam")
	await click("verify")
	await click("prepare")
	await click("Target_person")
	await click("ConfirmContain_person")
	check(game.model.s.mode=="dead" and game.modal=="death","actual wrong containment death")
	await click("RewindDeath")
	await click("Checkpoint_inspect")
	await click("verify")
	await click("prepare")
	await click("Target_boundary")
	await click("ConfirmContain_boundary")
	await click("return_success")
	await click("PutAway")
	check(game.model.s.cards.size()==1,"actual UI complete")
	await click("Collection")
	check(game.modal_layer.find_children("Card_*","Button",true,false).size()==30,"all thirty UI slots")
	await click("Card_M01")
	await click("StartAuto")
	check(game.model.s.idle.active,"actual card starts repeat")
	await click("FloorPlan")
	await click("Map_desk")
	game.tick_simulation(45)
	await click("FloorPlan")
	await click("Map_entry")
	await click("Delivery")
	await click("Claim")
	check(game.model.s.bag.size()>0 and game.model.s.inbox.is_empty(),"actual claim works while away")
	game.close_modal()
	await click("FloorPlan")
	await click("Map_desk")
	await click("Workbench")
	await click("DecomposeAll")
	await click("OpenSkills")
	await click("Upgrade_perception")
	check(game.model.s.skills.perception>1,"actual resource-to-ability path")
	game.close_modal()
	await click("FloorPlan")
	await click("Map_entry")
	await click("Peephole")
	check(game.model.s.room=="peephole","peephole reachable")
	game.tick_simulation(19)
	check(game.content.get_node("IdleShot").texture.resource_path.ends_with("03.png"),"peephole shows current stage")
	await click("Pause")
	var saved = game.model.export_state()
	game.tick_simulation(200)
	check(game.model.s==saved,"UI pause stops clock")
	await click("Resume")
	await click("LeavePeephole")
	await click("FloorPlan")
	await click("Map_bedroom")
	await click("Timer")
	await click("Pomo5")
	await click("PomoToggle")
	game.tick_simulation(10)
	check(game.model.s.pomo.remaining==290,"actual timer independent")
	game.close_modal()
	root.size = Vector2i(1280,800)
	await process_frame
	await click("FloorPlan")
	await click("Map_desk")
	await click("Abilities")
	check(game.modal=="skills","UI handles changed aspect ratio")
	game.queue_free()
	await process_frame

func _initialize() -> void:
	call_deferred("run")

func run() -> void:
	model_checks()
	await ui_checks()
	print("FULL_TEST ",checks," checks, ",failures," failures")
	quit(0 if failures==0 else 1)
